on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ap-northeast-1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.0.0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12.1
      - run: pip install psycopg2-binary==2.9.5 -t src/python
      - run: npm install
      - run: npx cdk deploy
